### ISSUE TITLE
[BUG] some examples don't run - check & fix

### ISSUE THREAD

**Issue by mkucmus** [shopware/frontends#678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

check all examples and fix:

-   "mollie-credit-card",
-   "adyen-dropin-component",
-   "commercial-quick-order",

### Environment

```markdown
- OS:
- Node:
- pnpm:
```

```[tasklist]
### Tasks
- [x] mollie-credit-card
- [x] adyen-dropin-component
- [x] commercial-quick-order
```

**Comment by mkucmus** [comment]
closed via #786 #817 #827
